### ISSUE TITLE
xml-conduit failed to parse HTML, with unclear message.

### ISSUE THREAD

**Issue by Magicloud** [snoyberg/xml#131]
The webpage is https://www.nasdaq.com/symbol/amzn. Works with xmllint tool.

But parsing it with xml-conduit, I got `Left (ParseError {errorContexts = [], errorMessage = "Failed reading: takeWhile1", errorPosition = 2:1 (2)})` when calling fromDocument.

The message is not quite clear to me. From a closed issue here, seems like related to invalid chars. So I set `psDecodeIllegalCharacters = \_ -> Just ' '` in ParseSettings, did not help.

**Comment by quasicomputational** [comment]
There are a couple of things going on here.

* That page is served as `text/html`, so parsing it with an XML parser isn't expected to work anyway. Try with `html-conduit` instead.

* The page *does* seem to be making some effort to support polyglot HTML/XML, but it's getting a few things wrong: the elements aren't in the HTML namespace (which doesn't affect XML well-formedness, but does keep it from being correct XHTML), it references the `nbsp` entity without using a DTD, and one of the `meta` elements doesn't have a close tag nor is it self-closing (both of which does mean it's not well-formed XML, and which an XML parser must fail on; I'd call it a bug in `xmllint` if it doesn't reject it). I don't know if that's the source of the parsing failure; there might be other non-XML stuff in there. All of these are basically caused by the prior point: the document doesn't claim to be XML, so parsing it as XML is on very shaky ground.

* Error messages from `attoparsec`, which is the parser combinator library that `xml-conduit` uses, are notoriously horrible, unfortunately.

**Comment by Magicloud** [comment]
@quasicomputational forgot the parseLBS in html-conduit. Thanks.
