### ISSUE TITLE
Preferred version on hackage below 1.9.0.0

### ISSUE THREAD

**Issue by phuhl** [snoyberg/xml#156]
Hi there, not sure if this is intentional or not, just wanted to check back on it:

According to hackage, the preferred version is `<= 1.9`, thus (if I understand the system correct) 1.8.0.1 as, according to https://pvp.haskell.org/ e.g.  `2.0.1.0 > 2.0.1` is true.

This is also reflected by the colors of the versions on hackage:
![org_20210116_133605_W5Bozs](https://user-images.githubusercontent.com/16835755/104812047-d06ccb80-57ff-11eb-9241-d8a046af8523.jpg)

Is this intentional? If so, why is 1.9.0.0 not preferred and why is the preferred version given as `<= 1.9` instead the less confusing `< 1.9` ?

Thanks :)

**Comment by k0ral** [comment]
This is a double-mistake (1/ using `<=` instead of `<` 2/ using `1.9` instead of `1.9.0.0`) that ends-up having the intended result (setting `1.9.0.0` as *unpreferred* version).

The rationale for having `1.9.0.0` as *unpreferred* is described in [this comment](https://github.com/snoyberg/xml/pull/93#issuecomment-275208946), but considering that `1.9.0.0` has been released for several months, it's time to make it the default one.

Thank you for bringing that up !
