### ISSUE TITLE
Pretty printing adds an additional newline at the top if XML declaration not printed

### ISSUE THREAD

**Issue by moll** [snoyberg/xml#196]
Hey,

Thanks for your continued maintenance of XML Conduit!

This is a tiny issue, but I noticed that the pretty-printing mechanism assumes an XML declaration was always printed, and appends a newline to it:
https://github.com/snoyberg/xml/blob/aa963de6af8734ae98ecd8ec5f82c9378f871671/xml-conduit/src/Text/XML/Stream/Render.hs#L308-L311

If no XML declaration was printed (using `rsXMLDeclaration = False`), it results in an unnecessary newline at the beginning.

Cheers

**Comment by k0ral** [comment]
I haven't tested it, but your analysis sounds correct to me.

I'm brought to question the current implementation of `prettify`, because:
- it implements pretty-printing at `Event` level, which sounds like the wrong layer to me ; as a consequence, and as mentioned in the associated documentation, "this can change the meaning of your XML"
- it's public, despite being redundant (API-wise) with calling `renderBytes` or `renderBuilder` with `rsPretty = true`

If I were to fix this, I would probably consider dropping `prettify` altogether, and reimplementing a _private_ equivalent at `ByteString` level.

**Comment by moll** [comment]
I personally wouldn't be opposed to removing this functionality entirely from XML Conduit in favor of everyone copying/implementing their own. It's very subjective and to handle prettifying properly, would need to have a bunch of configurable knobs. The first thing I noticed was it used 4 spaces to indent whereas I generally prefer tabs. Then there's the possibility of wrapping and indenting attributes if a line gets too long etc.

Like you highlighted, it changes the meaning by placing whitespace within tags. I can imagine desiring visual indenting without affecting the result. Another knob, and that'd require trickery with `>` symbols to have whitespace within a tag name where it doesn't affect parsing.

**Comment by k0ral** [comment]
Given that `xml-conduit` is in life-support, and as long as the pretty-printing feature doesn't get in the way of any development, I feel no urge to deprive users of that feature (if any), no matter how undesired it may be.

Nonetheless, I think we should signal our intent to get rid of it at some point in the future, so I suggest we attach a deprecation notice to both `prettify` and `rsPretty`, and freeze their imperfect, arbitrary implementation as is.

What do you think ?

**Comment by k0ral** [comment]
Deprecation notice added in [`1.9.1.4` release](https://hackage.haskell.org/package/xml-conduit-1.9.1.4).

Thank you for raising the issue.

**Comment by ulidtko** [comment]
Hi @k0ral @moll, I've got a project with `-Wall -Werror`. On routine maintenance upgrade, got this deprecation.

Not entirely clear to me: **what's the migration path**?

In a hurry, how am I supposed to fix the warning, while keeping the functionality of xml's pretty-printing ?

I won't obsess about absolute control of indentation & every other aspect of style (although that's [not available][1] anyway AFAICS) — the on/off switch `pretty: True` is the right level of granularity for my purposes.

The reason is that whatever-arbitrary-but-consistent formatting style — is better in my use-case then the formatting menagerie in user-submitted files, which are choke-full with utter chaos.

Thoughts? Suggestions?.. Please don't tell me I'm stuck with an _xml library_ that forces me to roll-my-own prettifying function.

[1]: https://hackage.haskell.org/package/xml-conduit-1.9.1.4/docs/Text-XML-Stream-Render.html#t:RenderSettings

**Comment by k0ral** [comment]
At the time I added the deprecation notice, the migration path I had in mind was either of the following:
1. copy the `prettify` [implementation](https://github.com/snoyberg/xml/blob/18bfda2254c2780fe4cd26019664a550a16a519c/xml-conduit/src/Text/XML/Stream/Render.hs#L298) inside your project (and tune it as you see fit)
2. reformat the XML document outside `xml-conduit`, e.g. using `xmllint --format` from [libxml2](https://gitlab.gnome.org/GNOME/libxml2) 

I've just reviewed again the current "prettifying" implementation, and I've realized it actually leaks outside the `prettify` function ([here](https://github.com/snoyberg/xml/blob/18bfda2254c2780fe4cd26019664a550a16a519c/xml-conduit/src/Text/XML/Stream/Render.hs#L228)), which partially invalidates migration path (1). That review was also the opportunity to reassert my reluctance to maintain the current implementation (let alone have it evolve.)

Regarding migration path (2), it involves a subprocess instead of library functions, which is admittedly less than ideal.

The fact that it breaks `-Wall` with (from what I understand) no way to silence that specific deprecation notice, is indeed problematic.

I'd like to offer an alternate course of actions:
- move `prettify` function in an `*.Internal` module, with no deprecation notice, but a comment explaining the caveats and the fact that it won't disappear until a satisfying migration path is provided
- remove `rsPretty`

This would serve as a _caveat emptor_ for `prettify`, without the hindrance of a compilation warning.

What do you think ?

**Comment by ulidtko** [comment]
Great @k0ral , that sounds workable 👍
