### ISSUE TITLE
Text.XML.Stream.Parse.choose seems to be awkward to use.

### ISSUE THREAD

**Issue by seanparsons** [snoyberg/xml#72]
The `choose` method seems to be quite troublesome to use:

```haskell
getTagContent :: Name -> Consumer Event IO (Maybe (Name, Text))
getTagContent tag = fmap (\content -> fmap (\c -> (tag, c)) content) $ tagIgnoreAttrs tag content

getTagsContent :: [Name] -> Consumer Event IO (Maybe (Name, Text))
getTagsContent tags = choose $ (fmap getTagContent tags)
```

The compile fails with:

```
    Couldn't match type ‘ConduitM Event o0 IO (Maybe (Name, Text))’
                   with ‘forall o1. ConduitM Event o1 IO (Maybe (Name, Text))’
    Expected type: Name -> Consumer Event IO (Maybe (Name, Text))
      Actual type: Name -> ConduitM Event o0 IO (Maybe (Name, Text))
    In the first argument of ‘fmap’, namely ‘getTagContent’
    In the second argument of ‘($)’, namely ‘(fmap getTagContent tags)’
```

See also (someone else having this issue): http://stackoverflow.com/questions/33606038/xml-conduit-combining-tagparsers

Asking in #haskell-beginners on Freenode there was a suggestion that the forall in the expansion of Consumer was at the root of this, which seems to make sense, but I've been unable to determine why. Removing the type definition has no material effect on the error either.

**Comment by k0ral** [comment]
It boils down to the distinction between `[forall a. a]` and `forall a. [a]`. As I don't feel confident to explain it myself, [here][1] is an article on the topic.
The `choose` combinator is impacted due to its signature enforcing a `[forall a. a]` pattern, but any other wrapping around `Consumer i m a` may result in the same error. That's why I personally always use the slightly more verbose `ConduitM i o m a` in signatures, so that the `forall` keyword is implicitly moved to top-level, which is what I want most of the time.

[1]: https://en.wikibooks.org/wiki/Haskell/Existentially_quantified_types
